superdock:
  
  version: 2.0.0
  
  id: my_project
  name: MyProject
  desc: My Project Starter
  
  owner: Superdock
  
  team:
    - name: Yannick
      role: Lead Developper
      email: yannick@superdock.dev
    - name: Brayan
      role: Developer Backend
      email: brayan@superdock.dev
    - name: Hugo
      role: Developer Frontend
      email: hugo@superdock.dev
    - name: Jordan
      role: Project Manager
      email: jordan@superdock.dev
  
  links:
    - Tickets: https://ppr.superdock.com
    - Documentation: https://docs.superdock.com
    - Specifications: https://spec.superdock.com
    - Design: https://spec.superdock.com
  
  services:
    nginx: 1.23.1
    node: 16.17.0
    mysql: 8.0.30
    adminer: latest
    redis: 7.0.4
    commander: latest
    mailhog: latest
    
  projects:

    frontend:
      local:
        domain: superdock.dev
        port: 3000
      staging:
        domain: staging.superdock.com
        port: 3000
      production:
        domain: superdock.com
        port: 3000

    backend:
      local:
        domain: admin.superdock.dev
        port: 3001
      staging:
        domain: admin.staging.superdock.com
        port: 3001
      production:
        domain: admin.superdock.com
        port: 3001

    api:
      local:
        domain: api.superdock.dev
        port: 3002
      staging:
        domain: api.staging.superdock.com
        port: 3002
      production:
        domain: api.superdock.com
        port: 3002