version: "3.9"

services:

  nginx:
    image: nginx:${SUPERDOCK_NGINX_VERSION}
    container_name: superdock_nginx
    stdin_open: true
    tty: true
    ports:
      - 80:80
      - 443:443
    links:
      - adminer
      - mailhog
      - rediscommander
    depends_on:
      - adminer
      - mailhog
      - rediscommander
    volumes:
      - ${SUPERDOCK_PATH_PROJECT}/superdock/certificates:/etc/nginx/ssl:ro
      - ${SUPERDOCK_PATH_SERVICES}/certificates:/etc/nginx/ssl_tools:ro
      - ${SUPERDOCK_PATH_SERVICES}/nginx/templates:/etc/nginx/templates
      - ${SUPERDOCK_PATH_SERVICES}/nginx/entrypoint:/docker-entrypoint.d
    environment:
      - NGINX_HOST_1=${SUPERDOCK_DOMAIN_1}
      - NGINX_PORT_1=${SUPERDOCK_PORT_1}
      - NGINX_PORT_DEV_1=${SUPERDOCK_PORT_DEV_1}
      - NGINX_HOST_2=${SUPERDOCK_DOMAIN_2}
      - NGINX_PORT_2=${SUPERDOCK_PORT_2}
      - NGINX_PORT_DEV_2=${SUPERDOCK_PORT_DEV_2}
      - NGINX_HOST_3=${SUPERDOCK_DOMAIN_3}
      - NGINX_PORT_3=${SUPERDOCK_PORT_3}
      - NGINX_PORT_DEV_3=${SUPERDOCK_PORT_DEV_3}
      - NGINX_HOST_4=${SUPERDOCK_DOMAIN_4}
      - NGINX_PORT_4=${SUPERDOCK_PORT_4}
      - NGINX_PORT_DEV_4=${SUPERDOCK_PORT_DEV_4}
      - NGINX_HOST_5=${SUPERDOCK_DOMAIN_5}
      - NGINX_PORT_5=${SUPERDOCK_PORT_5}
      - NGINX_PORT_DEV_5=${SUPERDOCK_PORT_DEV_5}

  database:
    image: mysql:${SUPERDOCK_MYSQL_VERSION}
    container_name: superdock_database
    stdin_open: true
    tty: true
    ports:
      - 3306:3306
    cap_add:
      - SYS_NICE
    volumes:
      - ${SUPERDOCK_PATH_PROJECT}/superdock/docker/mysql:/var/lib/mysql
      - ${SUPERDOCK_PATH_SERVICES}/mysql/init:/docker-entrypoint-initdb.d
      - ${SUPERDOCK_PATH_PROJECT}/superdock/databases:/superdock/databases
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-authentication-plugin=mysql_native_password --max_allowed_packet=32505856
    environment:
      MYSQL_ROOT_PASSWORD: root
      # MYSQL_USER: dev
      # MYSQL_PASSWORD: dev
      # MYSQL_DATABASE: dev

  search:
    image: getmeili/meilisearch:v0.28
    container_name: superdock_search
    stdin_open: true
    tty: true
    ports:
      - 7700:7700
    environment:
      #MEILI_MASTER_KEY: MASTER_KEY

  socket:
    image: quay.io/soketi/soketi:1.0-16-debian
    container_name: superdock_socket
    stdin_open: true
    tty: true
    ports:
      - 6001:6001
      - 9601:9601

  drive:
    image: minio/minio
    container_name: superdock_drive
    stdin_open: true
    tty: true
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - ${SUPERDOCK_PATH_PROJECT}/superdock/docker/drive:/data
    command: server --console-address ":9001" /data
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password

  adminer:
    image: adminer:${SUPERDOCK_ADMINER_VERSION}
    container_name: superdock_adminer
    stdin_open: true
    tty: true
    ports:
      - 8080:8080

  mailhog:
    image: mailhog/mailhog:${SUPERDOCK_MAILHOG_VERSION}
    container_name: superdock_mailhog
    stdin_open: true
    tty: true
    ports:
      - 1025:1025
      - 8025:8025

  redis:
    image: redis:${SUPERDOCK_REDIS_VERSION}
    container_name: superdock_redis
    stdin_open: true
    tty: true
    ports:
      - 6379:6379

  rediscommander:
    image: rediscommander/redis-commander:${SUPERDOCK_COMMANDER_VERSION}
    container_name: superdock_rediscommander
    hostname: rediscommander
    stdin_open: true
    tty: true
    ports:
      - 8081:8081
    environment:
      - REDIS_HOSTS=local:redis:6379